// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package org.example.winsignin.rust

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_winsignin_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_winsignin_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "winsignin"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "winsignin"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_winsignin_checksum_func_get_account(
    ): Int
    external fun uniffi_winsignin_checksum_func_get_number_code(
    ): Int
    external fun uniffi_winsignin_checksum_func_get_rollcalls(
    ): Int
    external fun uniffi_winsignin_checksum_func_login(
    ): Int
    external fun uniffi_winsignin_checksum_func_refresh_session(
    ): Int
    external fun uniffi_winsignin_checksum_func_sign_number(
    ): Int
    external fun uniffi_winsignin_checksum_func_sign_qr(
    ): Int
    external fun uniffi_winsignin_checksum_func_sign_radar(
    ): Int
    external fun uniffi_winsignin_checksum_func_sign_radar_empty(
    ): Int
    external fun uniffi_winsignin_checksum_func_solve_radar_target(
    ): Int
    external fun uniffi_winsignin_checksum_func_verify_signed(
    ): Int
    external fun ffi_winsignin_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "winsignin"))
        
    }
    external fun uniffi_winsignin_fn_func_get_account(`cookie`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_get_number_code(`cookie`: RustBuffer.ByValue,`rollcallId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_get_rollcalls(`cookie`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_login(`username`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,`bfp`: RustBuffer.ByValue,`rememberMe`: Byte,`casCookie`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_refresh_session(`casCookie`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_sign_number(`cookie`: RustBuffer.ByValue,`deviceId`: RustBuffer.ByValue,`rollcallId`: RustBuffer.ByValue,`numberCode`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_sign_qr(`cookie`: RustBuffer.ByValue,`deviceId`: RustBuffer.ByValue,`rawQr`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_sign_radar(`cookie`: RustBuffer.ByValue,`deviceId`: RustBuffer.ByValue,`rollcallId`: RustBuffer.ByValue,`latitude`: Double,`longitude`: Double,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_sign_radar_empty(`cookie`: RustBuffer.ByValue,`rollcallId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_solve_radar_target(`points`: RustBuffer.ByValue,`distances`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_winsignin_fn_func_verify_signed(`cookie`: RustBuffer.ByValue,`rollcallId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_winsignin_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_winsignin_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_winsignin_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_winsignin_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_winsignin_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_winsignin_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_winsignin_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_winsignin_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_winsignin_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_winsignin_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_winsignin_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_winsignin_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_winsignin_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_winsignin_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_winsignin_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_winsignin_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_winsignin_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_winsignin_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if ((lib.uniffi_winsignin_checksum_func_get_account() and 0xFFFF) != 50463) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_get_number_code() and 0xFFFF) != 5308) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_get_rollcalls() and 0xFFFF) != 30334) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_login() and 0xFFFF) != 7257) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_refresh_session() and 0xFFFF) != 30004) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_sign_number() and 0xFFFF) != 34948) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_sign_qr() and 0xFFFF) != 43782) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_sign_radar() and 0xFFFF) != 32617) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_sign_radar_empty() and 0xFFFF) != 22619) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_solve_radar_target() and 0xFFFF) != 34553) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_winsignin_checksum_func_verify_signed() and 0xFFFF) != 4699) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * 当前账号信息。拿不到时 ok=false，message 里是原因。
 */
data class AccountInfo (
    var `ok`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `id`: kotlin.String
    , 
    var `name`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAccountInfo: FfiConverterRustBuffer<AccountInfo> {
    override fun read(buf: ByteBuffer): AccountInfo {
        return AccountInfo(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: AccountInfo) = (
            FfiConverterBoolean.allocationSize(value.`ok`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`)
    )

    override fun write(value: AccountInfo, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ok`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
    }
}



/**
 * 一个经纬度点（雷达三边定位的探测点）。
 */
data class GeoPoint (
    var `lat`: kotlin.Double
    , 
    var `lon`: kotlin.Double
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeGeoPoint: FfiConverterRustBuffer<GeoPoint> {
    override fun read(buf: ByteBuffer): GeoPoint {
        return GeoPoint(
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: GeoPoint) = (
            FfiConverterDouble.allocationSize(value.`lat`) +
            FfiConverterDouble.allocationSize(value.`lon`)
    )

    override fun write(value: GeoPoint, buf: ByteBuffer) {
            FfiConverterDouble.write(value.`lat`, buf)
            FfiConverterDouble.write(value.`lon`, buf)
    }
}



/**
 * 自动登录结果。成功时 cookie 是 lms 域下的会话串，
 * cas_cookie 是 CAS 域 cookie（CASTGC 等），由调用方按账号持久化。
 */
data class LoginResult (
    var `ok`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `cookie`: kotlin.String
    , 
    var `casCookie`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLoginResult: FfiConverterRustBuffer<LoginResult> {
    override fun read(buf: ByteBuffer): LoginResult {
        return LoginResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: LoginResult) = (
            FfiConverterBoolean.allocationSize(value.`ok`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterString.allocationSize(value.`cookie`) +
            FfiConverterString.allocationSize(value.`casCookie`)
    )

    override fun write(value: LoginResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ok`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterString.write(value.`cookie`, buf)
            FfiConverterString.write(value.`casCookie`, buf)
    }
}



/**
 * 从点名里直接读出的数字签到码。
 */
data class NumberCodeResult (
    var `ok`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `code`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeNumberCodeResult: FfiConverterRustBuffer<NumberCodeResult> {
    override fun read(buf: ByteBuffer): NumberCodeResult {
        return NumberCodeResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: NumberCodeResult) = (
            FfiConverterBoolean.allocationSize(value.`ok`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterString.allocationSize(value.`code`)
    )

    override fun write(value: NumberCodeResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ok`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterString.write(value.`code`, buf)
    }
}



/**
 * 三边定位算出的目标点。
 */
data class RadarTarget (
    var `ok`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `lat`: kotlin.Double
    , 
    var `lon`: kotlin.Double
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRadarTarget: FfiConverterRustBuffer<RadarTarget> {
    override fun read(buf: ByteBuffer): RadarTarget {
        return RadarTarget(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: RadarTarget) = (
            FfiConverterBoolean.allocationSize(value.`ok`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterDouble.allocationSize(value.`lat`) +
            FfiConverterDouble.allocationSize(value.`lon`)
    )

    override fun write(value: RadarTarget, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ok`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterDouble.write(value.`lat`, buf)
            FfiConverterDouble.write(value.`lon`, buf)
    }
}



/**
 * 一条点名记录（只取界面要用的字段）。
 */
data class Rollcall (
    var `id`: kotlin.String
    , 
    var `courseTitle`: kotlin.String
    , 
    var `title`: kotlin.String
    , 
    var `isNumber`: kotlin.Boolean
    , 
    var `isRadar`: kotlin.Boolean
    , 
    var `isExpired`: kotlin.Boolean
    , 
    var `status`: kotlin.String
    , 
    var `rollcallTime`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRollcall: FfiConverterRustBuffer<Rollcall> {
    override fun read(buf: ByteBuffer): Rollcall {
        return Rollcall(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Rollcall) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`courseTitle`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterBoolean.allocationSize(value.`isNumber`) +
            FfiConverterBoolean.allocationSize(value.`isRadar`) +
            FfiConverterBoolean.allocationSize(value.`isExpired`) +
            FfiConverterString.allocationSize(value.`status`) +
            FfiConverterString.allocationSize(value.`rollcallTime`)
    )

    override fun write(value: Rollcall, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`courseTitle`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterBoolean.write(value.`isNumber`, buf)
            FfiConverterBoolean.write(value.`isRadar`, buf)
            FfiConverterBoolean.write(value.`isExpired`, buf)
            FfiConverterString.write(value.`status`, buf)
            FfiConverterString.write(value.`rollcallTime`, buf)
    }
}



/**
 * 点名列表结果。
 */
data class RollcallsResult (
    var `ok`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `rollcalls`: List<Rollcall>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRollcallsResult: FfiConverterRustBuffer<RollcallsResult> {
    override fun read(buf: ByteBuffer): RollcallsResult {
        return RollcallsResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeRollcall.read(buf),
        )
    }

    override fun allocationSize(value: RollcallsResult) = (
            FfiConverterBoolean.allocationSize(value.`ok`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterSequenceTypeRollcall.allocationSize(value.`rollcalls`)
    )

    override fun write(value: RollcallsResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ok`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterSequenceTypeRollcall.write(value.`rollcalls`, buf)
    }
}



/**
 * 签到结果。[distance] 只在雷达签到被判"太远"时返回，单位米（服务器算的）。
 */
data class SignResult (
    var `success`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `distance`: kotlin.Double?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSignResult: FfiConverterRustBuffer<SignResult> {
    override fun read(buf: ByteBuffer): SignResult {
        return SignResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalDouble.read(buf),
        )
    }

    override fun allocationSize(value: SignResult) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterOptionalDouble.allocationSize(value.`distance`)
    )

    override fun write(value: SignResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterOptionalDouble.write(value.`distance`, buf)
    }
}



/**
 * 签到后回查的确认结果。[status] 是服务器给的本人状态。
 */
data class VerifyResult (
    var `ok`: kotlin.Boolean
    , 
    var `message`: kotlin.String
    , 
    var `status`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeVerifyResult: FfiConverterRustBuffer<VerifyResult> {
    override fun read(buf: ByteBuffer): VerifyResult {
        return VerifyResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: VerifyResult) = (
            FfiConverterBoolean.allocationSize(value.`ok`) +
            FfiConverterString.allocationSize(value.`message`) +
            FfiConverterString.allocationSize(value.`status`)
    )

    override fun write(value: VerifyResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ok`, buf)
            FfiConverterString.write(value.`message`, buf)
            FfiConverterString.write(value.`status`, buf)
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalDouble: FfiConverterRustBuffer<kotlin.Double?> {
    override fun read(buf: ByteBuffer): kotlin.Double? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterDouble.read(buf)
    }

    override fun allocationSize(value: kotlin.Double?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterDouble.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Double?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterDouble.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceDouble: FfiConverterRustBuffer<List<kotlin.Double>> {
    override fun read(buf: ByteBuffer): List<kotlin.Double> {
        val len = buf.getInt()
        return List<kotlin.Double>(len) {
            FfiConverterDouble.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Double>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterDouble.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Double>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterDouble.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeGeoPoint: FfiConverterRustBuffer<List<GeoPoint>> {
    override fun read(buf: ByteBuffer): List<GeoPoint> {
        val len = buf.getInt()
        return List<GeoPoint>(len) {
            FfiConverterTypeGeoPoint.read(buf)
        }
    }

    override fun allocationSize(value: List<GeoPoint>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeGeoPoint.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<GeoPoint>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeGeoPoint.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeRollcall: FfiConverterRustBuffer<List<Rollcall>> {
    override fun read(buf: ByteBuffer): List<Rollcall> {
        val len = buf.getInt()
        return List<Rollcall>(len) {
            FfiConverterTypeRollcall.read(buf)
        }
    }

    override fun allocationSize(value: List<Rollcall>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeRollcall.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Rollcall>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeRollcall.write(it, buf)
        }
    }
}
        /**
         * 取当前账号信息：`GET /api/profile`，顺便验证会话还有效。
         */ fun `getAccount`(`cookie`: kotlin.String): AccountInfo {
            return FfiConverterTypeAccountInfo.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_get_account(
    
        
        FfiConverterString.lower(`cookie`),_status)
}
    )
    }
    

        /**
         * 直接从点名里读数字签到码：`GET /api/rollcall/{id}/student_rollcalls`。
         */ fun `getNumberCode`(`cookie`: kotlin.String, `rollcallId`: kotlin.String): NumberCodeResult {
            return FfiConverterTypeNumberCodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_get_number_code(
    
        
        FfiConverterString.lower(`cookie`),
        FfiConverterString.lower(`rollcallId`),_status)
}
    )
    }
    

        /**
         * 取当前账号的点名列表。
         */ fun `getRollcalls`(`cookie`: kotlin.String): RollcallsResult {
            return FfiConverterTypeRollcallsResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_get_rollcalls(
    
        
        FfiConverterString.lower(`cookie`),_status)
}
    )
    }
    

        /**
         * 账号密码自动登录：走完整条金智 CAS 网关链，成功返回 lms 会话 cookie。
         * [remember_me] 勾选"记住我"时向 CAS 申请长效 TGT（14 天免登录）。
         * [cas_cookie] 传上次保存的 CAS cookie， CASTGC 还有效就能免密直接落回 lms。
         */ fun `login`(`username`: kotlin.String, `password`: kotlin.String, `bfp`: kotlin.String, `rememberMe`: kotlin.Boolean, `casCookie`: kotlin.String): LoginResult {
            return FfiConverterTypeLoginResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_login(
    
        
        FfiConverterString.lower(`username`),
        FfiConverterString.lower(`password`),
        FfiConverterString.lower(`bfp`),
        FfiConverterBoolean.lower(`rememberMe`),
        FfiConverterString.lower(`casCookie`),_status)
}
    )
    }
    

        /**
         * 用已保存的 CAS cookie 静默刷新会话（免密），CASTGC 过期就失败。
         */ fun `refreshSession`(`casCookie`: kotlin.String): LoginResult {
            return FfiConverterTypeLoginResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_refresh_session(
    
        
        FfiConverterString.lower(`casCookie`),_status)
}
    )
    }
    

        /**
         * 数字签到：rollcall_id + 4 位密码。
         */ fun `signNumber`(`cookie`: kotlin.String, `deviceId`: kotlin.String, `rollcallId`: kotlin.String, `numberCode`: kotlin.String): SignResult {
            return FfiConverterTypeSignResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_sign_number(
    
        
        FfiConverterString.lower(`cookie`),
        FfiConverterString.lower(`deviceId`),
        FfiConverterString.lower(`rollcallId`),
        FfiConverterString.lower(`numberCode`),_status)
}
    )
    }
    

        /**
         * 扫码原文 -> 解析 -> 二维码签到接口 -> 结果。
         */ fun `signQr`(`cookie`: kotlin.String, `deviceId`: kotlin.String, `rawQr`: kotlin.String): SignResult {
            return FfiConverterTypeSignResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_sign_qr(
    
        
        FfiConverterString.lower(`cookie`),
        FfiConverterString.lower(`deviceId`),
        FfiConverterString.lower(`rawQr`),_status)
}
    )
    }
    

        /**
         * 位置（雷达）签到：提交经纬度（按 GCJ02），服务器据此算出与点名位置的距离。
         */ fun `signRadar`(`cookie`: kotlin.String, `deviceId`: kotlin.String, `rollcallId`: kotlin.String, `latitude`: kotlin.Double, `longitude`: kotlin.Double): SignResult {
            return FfiConverterTypeSignResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_sign_radar(
    
        
        FfiConverterString.lower(`cookie`),
        FfiConverterString.lower(`deviceId`),
        FfiConverterString.lower(`rollcallId`),
        FfiConverterDouble.lower(`latitude`),
        FfiConverterDouble.lower(`longitude`),_status)
}
    )
    }
    

        /**
         * 雷达签到（空答案方案）：PUT body 为空 `{}`，不带坐标、不带 api_version。
         * 服务器可能直接判到场，调用方需再 verify_signed 确认。
         */ fun `signRadarEmpty`(`cookie`: kotlin.String, `rollcallId`: kotlin.String): SignResult {
            return FfiConverterTypeSignResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_sign_radar_empty(
    
        
        FfiConverterString.lower(`cookie`),
        FfiConverterString.lower(`rollcallId`),_status)
}
    )
    }
    

        /**
         * 三边定位：给 3 个探测点和对应距离，算出目标经纬度。
         */ fun `solveRadarTarget`(`points`: List<GeoPoint>, `distances`: List<kotlin.Double>): RadarTarget {
            return FfiConverterTypeRadarTarget.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_solve_radar_target(
    
        
        FfiConverterSequenceTypeGeoPoint.lower(`points`),
        FfiConverterSequenceDouble.lower(`distances`),_status)
}
    )
    }
    

        /**
         * 签到后回查：拉点名列表，找这场点名看本人 status 是否 on_call_fine。
         */ fun `verifySigned`(`cookie`: kotlin.String, `rollcallId`: kotlin.String): VerifyResult {
            return FfiConverterTypeVerifyResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_winsignin_fn_func_verify_signed(
    
        
        FfiConverterString.lower(`cookie`),
        FfiConverterString.lower(`rollcallId`),_status)
}
    )
    }
    


